### PR TITLE
Add airline themes

### PR DESCRIPTION
**Pull request by tiegs**
I've spent a little time and added airline-themes to the vim-theme - any interest pulling them into the official repo?
What would be required for it to be merged?

### CODE REVIEW

**Comment by M3nny** [comment]
Hi, is it an expected feature that in insert and visual mode the bar is darker while in replace and normal mode it is lighter and integrates well with the theme itself?

**Comment by tiegs** [comment]
Good catch - I took the theme from the nvim airline plugin and just modified it for vim - the bar changes there in the same way. So in all honesty I have no idea if it's intentional :)

I think it looks better with the bar matching the background in all modes and modified the theme accordingly.

**Comment by M3nny** [comment]
Sorry I didn't see this before, but is the orange color like that in neovim as well? Because it looks like the default one and it is the same for each variant
airline
airline-2

**Comment by tiegs** [comment]
Interesting - I was not aware of this. 
Its airline's warning section (in this case a message from airline-whitespace - hence its not visible all the time).

Its the same in neovim (same goes for the backgroud-issue above, I confirmed this now ). 
image
image
image

And yes it seems to be the default color. Since its a warning/error i think it's only appropriate for it to 'pop' a little - the default color matches the theme surprisingly well for that purpose :laughing:


I've gone ahead modified the theme to match the official styleguide (using peach, looked best imo), this is what I came up with:
image
image
image
image

PS: I've also used the opportunity to fix the whitespace-issues in the theme-files - they were great for testing tho :D

**Comment by M3nny** [comment]
That's great, thank you :D

**Pull request merged**
